### ISSUE TITLE
Error in new SVIGP function

### ISSUE THREAD

**Issue by ankitchiplunkar** [gpstuff-dev/gpstuff#1]
I am testing the new svigp function, for small datasets of the order 7000 points the function works well, but for high amount of data 70,000 points I am constantly error like the one below.

More over the error can be thrown after a few iterations (basically its pretty random), can you tell me how to solve this issue? 

```
iter=1/1000, e=-534639.756, de=Inf
iter=11/1000, e=65878.426, de=18512
Bad parameter values, decreasing mu2.
Error using GPSVI_G
The value of 'gpsvi_e_param' is invalid. It must satisfy the function: isstruct.

Error in gpsvi_g (line 40)
ip.parse(w, gp, x, y, varargin{:});

Error in svigp (line 296)
    g = gpsvi_g(w,gp,x(inds{i},:),y(inds{i},:), 'z', zi, ...

```

**Comment by avehtari** [comment]
Thanks for the report. Sorry for the delay, but I've been on vacation. I had a quick look now, and I think I know where the error is, but I have to make some experiments to verify,

**Comment by avehtari** [comment]
fixed
