### ISSUE TITLE
What is the relationship between parameter-initialization and prior?

### ISSUE THREAD

**Issue by kaare-mikkelsen** [gpstuff-dev/gpstuff#16]
Looking at the regression demos, there is a clear trend that the means of all priors are kept at the default (0), while the initial guesses are different (see, for instance, demo_regression_additive1.m). Is this supposed to indicate that the actual prior used in gp_optim is prior+initial guess? Otherwise it seems somewhat odd to use a student's t distribution centered around 0 as a prior for a length scale, which necessarily must be positive. 

if I have deduced the behavior correctly, I think it should be described a bit more prominently. Possibly appended to the help-texts for the priors functions.

**Comment by avehtari** [comment]
All hyperparameters which must be positive are constrained to be positive and thus when t-distribution with location parameter 0 is used for those hyperparameters, it effectively sets a half-t-distribution prior. We'll try to clarify this in the next release.

**Comment by kaare-mikkelsen** [comment]
so, to be clear, the initial guess does not interact with the prior?

**Comment by avehtari** [comment]
correct

**Comment by kaare-mikkelsen** [comment]
thanks
