### ISSUE TITLE
`gpmc_preds` broken (?): Ef and Varf end up having different dimensions

### ISSUE THREAD

**Issue by aa-m-sa** [gpstuff-dev/gpstuff#2]
I encountered most curious behaviour when trying to do a MCMC prediction at just one point:

```
[gp_rec,g,opt] = gp_mc(gp, etc)  % gp: lik_gaussian, gpcf_sexp
xt = 0.5; % instead of xt = linspace(something)
[Eft_mc, Varft_mc] = gp_pred(gp_rec, x, y, xt, etc)
```

`Eft_mc` is 1x1 as expected, but Varft_mc is a vector of size Nx1 (N being the number of samples), which I don't quite think is the intended behaviour. (Eft and Varft always have correctly a same dimension as `xt` if it has more than one element.)

Also, I think I found _where_ the bug is: in `gpmc_pred` we call `gpmc_preds`

```
[Efs, Varfs, lpys, Eys, Varys] = gpmc_preds(gp, x, y, varargin{:});
```

and at the end of `gpmc_preds.m` singleton-dimensions of `Vary` and `Varf` are squeezed out:

```
Varf=squeeze(Varf);
Vary=squeeze(Vary);
```

In the simple `lik_gaussian` case they were populated in the loop

```
if isfield(gp, 'latentValues') && ~isempty(gp.latentValues)
     % [...skip]
else 
  % Gaussian likelihood or Laplace/EP for latent values
  if nargout <= 2
    [Ef(:,i1), Varf(:,:,i1)] = gp_pred(Gp, x, y, xt, options);
  elseif nargout <=3
    [Ef(:,i1), Varf(:,:,i1), lpy(:,i1)] = gp_pred(Gp, x, y, xt, options);
  else
    [Ef(:,i1), Varf(:,:,i1), lpy(:,i1), Ey(:,i1), Vary(:,:,i1)] = gp_pred(Gp, x, y, xt, options); 
  end
end
```

Now if `xt = 1`, after the loop, Ef (and Ey) are sized 1 x k  and variances Varf (and Vary) 1 x 1 x k. Because of peculiar quirk of squeeze.m, the squeezed `Varf`(and `Vary`) get turned into k x 1 vectors while `Ef` (and `Ey`) remain 1 x k row vectors (which are then returned). 

 Thus when later in `gpmc_pred` their means are taken along the 2nd dimension,

```
  Ef=mean(Efs,2);
  Varf=mean(Varfs,2) + var(Efs,0,2);
  Ey=mean(Eys,2);
  Vary=mean(squeeze(Varys),2) + var(Eys,0,2);
```

`Ef, Ey` end up being 1x1, but `mean(Varys,2)` remain sized Nx1.

**Comment by avehtari** [comment]
Thanks for the detailed report! This was easy to fix by changing
 Varf=squeeze(Varf);
to 
 Varf=permute(Varf,[1 3 2]);

The fix should be available in github this or next week (we are in progress of making develop branch visible in github)

**Comment by avehtari** [comment]
fixed
