### ISSUE TITLE
Gradient equations for SVIGP

### ISSUE THREAD

**Issue by ghost** [gpstuff-dev/gpstuff#3]
Hi,

First of all, great work. This is not really an issue (maybe), just a question: I was having a look at the gradient equations for SVIGP, and it seems that the derivative matrices (DKuu, etc) are receiving the covariance matrices themselves (K_uu, etc) after the call to the covariance function. Maybe I am missing the point as to why, could you maybe point me to some reference showing this gradient derivation?

**Comment by avehtari** [comment]
SVIGP part was coded by Ville Tolvanen who is not around anymore. Ville's master thesis has some of the derivations https://aaltodoc.aalto.fi/bitstream/handle/123456789/13596/master_Tolvanen_Ville_2014.pdf
Have you read that?
