### ISSUE TITLE
Many functions cannot be compiled properly in Mac OS

### ISSUE THREAD

**Issue by lijing-lin** [gpstuff-dev/gpstuff#39]
`matlab_install('SuiteSparseOn')`

Warnings produced such as:

> mc/linuxCsource/bbmean.c:39:10: warning: incompatible pointer types assigning to 'const int *' from 'const mwSize *' (aka 'const unsigned long *') [-Wincompatible-pointer-types]
>     dims = mxGetDimensions(prhs[0]);
>          ^ ~~~~~~~~~~~~~~~~~~~~~~~~
> 

`bbmean.m` contains only:

> error('No mex-file for this architecture. See Matlab help and convert.m in ./linuxCsource or ./winCsource for help.')

Is it not meant to be used in Mac OS?

**Comment by jpvanhat** [comment]
GPstuff has been built for Linux and Windows and we have not tested it with Mac OS.
