### ISSUE TITLE
Input-dependent noise - what I'm doing wrong?

### ISSUE THREAD

**Issue by mh510** [gpstuff-dev/gpstuff#45]
The following toy example doesnt work, what I'm doing wrong?

```
%% code
clear; close all; clc; rng(42);

% - define ground truth
xlb = 0;
xub = 10;
objfcn = @(x) 2*x+1;
xgrid = linspace(xlb, xub, 1000)';
fgrid = objfcn(xgrid);

% - create data
ndata = 99;
s2nfcn = @(x) 0.01*x.^2+0.01;
x = sort(xlb+(xub-xlb)*rand(ndata, 1));
y = objfcn(x)+sqrt(s2nfcn(x)).*randn(ndata, 1);

% - set up gaussian process structure
gp = gp_set('lik', lik_inputdependentnoise, 'cf', {gpcf_sexp gpcf_exp}, 'jitterSigma2', 1e-8, 'comp_cf', {[1] [2]});
gp = gp_optim(gp, x, y);
[~, ~, ~, ymean, yvar] = gp_pred(gp, x, y, xgrid);

% - visualize
figure(1);
hold on; grid on;
plot(xgrid, fgrid, 'g');
plot(x, y, 'k+');
plot(xgrid, ymean, 'b');
plot(xgrid, ymean+3*sqrt(yvar), 'b--');
plot(xgrid, ymean-3*sqrt(yvar), 'b--');
```

**Comment by jpvanhat** [comment]
Hi,

I'm sorry for delay in my reply. The problem in your model is that your data follows exactly linear trend with large magnitude whereas your prior and initial values for the squared exponential covariance function parameters favor strongly fast varying and small magnitude processes. Hence, your prior penalizes the model so much that it is not able to fit the trend in your data. You can fix this by writing either

`
clear; close all; clc; rng(42);

% - define ground truth
xlb = 0;
xub = 10;
objfcn = @(x) 2*x+1;
xgrid = linspace(xlb, xub, 1000)';
fgrid = objfcn(xgrid);

% - create data
ndata = 99;
s2nfcn = @(x) 0.01*x.^2+0.01;
x = sort(xlb+(xub-xlb)*rand(ndata, 1));
y = objfcn(x)+sqrt(s2nfcn(x)).*randn(ndata, 1);

% - set up gaussian process structure
gp = gp_set('lik', lik_inputdependentnoise('sigma2', 0.1, 'sigma2_prior', prior_fixed), 'cf', {gpcf_sum('cf',{gpcf_sexp,gpcf_linear}) gpcf_exp}, 'jitterSigma2', 1e-8, 'comp_cf', {[1] [2]});
gp = gp_optim(gp, x, y);
[Ef, Varf, ~, ymean, yvar] = gp_pred(gp, x, y, xgrid);

% - visualize
figure(1);
hold on; grid on;
plot(xgrid, fgrid, 'g');
plot(x, y, 'k+');
plot(xgrid, ymean, 'b');
plot(xgrid, ymean+3*sqrt(yvar), 'b--');
plot(xgrid, ymean-3*sqrt(yvar), 'b--');
`

or 

`
%% code
clear; close all; clc; rng(42);

% - define ground truth
xlb = 0;
xub = 10;
objfcn = @(x) 2*x+1;
xgrid = linspace(xlb, xub, 1000)';
fgrid = objfcn(xgrid);

% - create data
ndata = 99;
s2nfcn = @(x) 0.01*x.^2+0.01;
x = sort(xlb+(xub-xlb)*rand(ndata, 1));
y = objfcn(x)+sqrt(s2nfcn(x)).*randn(ndata, 1);

% - set up gaussian process structure
gp = gp_set('lik', lik_inputdependentnoise, 'cf', {gpcf_sexp('lengthScale', 10, 'magnSigma2', 5, 'lengthScale_prior', prior_t('s2',10)) gpcf_exp}, 'jitterSigma2', 1e-8, 'comp_cf', {[1] [2]});
gp = gp_optim(gp, x, y);
[~, ~, ~, ymean, yvar] = gp_pred(gp, x, y, xgrid);

% - visualize
figure(1);
hold on; grid on;
plot(xgrid, fgrid, 'g');
plot(x, y, 'k+');
plot(xgrid, ymean, 'b');
plot(xgrid, ymean+3*sqrt(yvar), 'b--');
plot(xgrid, ymean-3*sqrt(yvar), 'b--');
`

**Comment by mh510** [comment]
Thank you very much!
