### ISSUE TITLE
Inverse-Distance Covariance Function

### ISSUE THREAD

**Issue by faridf** [gpstuff-dev/gpstuff#58]
Hello!

Thanks for making your code public. Is there any part of this code suppose to include the Inverse-Distance Kernel as it is suggested in this publication?
Minimum Mode Saddle Point Searches Using Gaussian Process
Regression with Inverse-Distance Covariance Function

[https://pubs.acs.org/doi/10.1021/acs.jctc.9b01038](url)

And if so, may I have access to it? 
Thanks!

**Comment by avehtari** [comment]
Hi, GPStuff is not actively developed and maintained any more, and that is why the inverse-distance kernel was not merged to this repo. If you are interested in using the minimum saddle point search for the energy surfaces, contact Hannes Jonsson who has led development of a more efficient code base which integrates also with the atomic simulation engine (ASE). If you want to replicate our experiments with the Matlab code, let me know, and I'll search the code for you.

**Comment by faridf** [comment]
Hi, thanks for your quick comment! I would be very glad to look into your Matlab codes if possible.
Thanks!

**Comment by avehtari** [comment]
I found the Python code (for GPy), but not yet the Matlab code. I emailed Olli-Pekka.

**Comment by faridf** [comment]
May I actually have a copy of the GPy script as well. It could help me out since I am developing in python as well.

**Comment by faridf** [comment]
Also thanks for reaching out to Olli-Pekka! I appreciate it.

**Comment by avehtari** [comment]
The Matlab code is now at https://users.aalto.fi/~ave/atomic_GP-NEB-dimer_2020-07-09.zip
The inverse-distance is in gpcf_sexpat.m

**Comment by faridf** [comment]
Thanks so much for sharing your code and I've been reading it and it's a great source for me.

I hope I'm not asking for much but but I could use the Python code that uses GPy as well. It would be very handy.

Thanks again!

**Comment by avehtari** [comment]
The Python code is now at https://users.aalto.fi/~ave/atomic_GPy-NEB-dimer_2020-07-09.zip
The dimer part has not been tested and may contain errors.
