### ISSUE TITLE
Error using GPEP_E

### ISSUE THREAD

**Issue by FabianMunozSilva** [gpstuff-dev/gpstuff#60]
Hi 
I am running a simple regression and I have this error
Error using GPEP_E
The value of 'w' is invalid. It must satisfy the function:
@(x)isempty(x)||(ischar(x)&&ismember(x,{'init','clearcache'}))||(isvector(x)&&isreal(x)&&all(isfinite(x)))||all(isnan(x)).
I would like to understand in which condition of the data this happen.

**Comment by jpvanhat** [comment]
Hi,
This is a check that the input for gpep_e function is of correct form. Could you send me the piece of code that produces the error.

Yours,

-Jarno

**Comment by FabianMunozSilva** [comment]
Hi Jarno. 
Thanks for the quick answer, but I found my mistake, happen that when I removed all the zero data the error stop, and I learned that the data should not have any zero in it.
Thanks again
Fabian

**Comment by jpvanhat** [comment]
Hi, 
Good, that the problem got solved so easily.

Yours,

-Jarno
